// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQskb8hFzVtwqt1zc3mVOmPc7JJ9hkzbg',
    appId: '1:1087797528615:web:02c0c3dd9e681772aca602',
    messagingSenderId: '1087797528615',
    projectId: 'carpark-cd8f3',
    authDomain: 'carpark-cd8f3.firebaseapp.com',
    storageBucket: 'carpark-cd8f3.appspot.com',
    measurementId: 'G-1BHWBJX418',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlxT2EppSBD2oiGOnWfZOrkl4Bh0Vdgfk',
    appId: '1:1087797528615:android:d97fb956f8ed1ea9aca602',
    messagingSenderId: '1087797528615',
    projectId: 'carpark-cd8f3',
    storageBucket: 'carpark-cd8f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuOcKntET5xnmvDEe0xh1tVoiInU3AHpE',
    appId: '1:1087797528615:ios:50583f8b385f36dcaca602',
    messagingSenderId: '1087797528615',
    projectId: 'carpark-cd8f3',
    storageBucket: 'carpark-cd8f3.appspot.com',
    iosBundleId: 'com.josephmp5.fleetingframes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuOcKntET5xnmvDEe0xh1tVoiInU3AHpE',
    appId: '1:1087797528615:ios:575720b2e4d0aedaaca602',
    messagingSenderId: '1087797528615',
    projectId: 'carpark-cd8f3',
    storageBucket: 'carpark-cd8f3.appspot.com',
    iosBundleId: 'com.example.fleetingframes.RunnerTests',
  );
}
